version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: viet1234
      MYSQL_DATABASE: yoga_support
      MYSQL_USER: vietpham102301
      MYSQL_PASSWORD: viet1234
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
